sudo: false
language: node_js
node_js:
  - "stable"
before_script:
  - "npm install -g markdown-link-check"
script:
  - "markdown-link-check ./README.md"
  - "markdown-link-check ./GEMS.md"
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
